// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Links*
 */
export interface FooterDocumentDataLinksItem {
  /**
   * linkedin field in *Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * facebook field in *Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].facebook
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * twitter field in *Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].twitter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * instagram field in *Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;
}

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterDocumentDataLinksItem>>;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Meta Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: footer.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: footer.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | RichTextSlice
  | AnnouncementsSlice
  | DownloadsSlice
  | FaqsSlice
  | WhenandWhereSlice
  | AgendaSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Date field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Location field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Title 1 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_one: prismic.KeyTextField;

  /**
   * Title 2 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_two: prismic.KeyTextField;

  /**
   * Title 3 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_three
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_three: prismic.KeyTextField;

  /**
   * Intro text field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.intro_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro_text: prismic.RichTextField;

  /**
   * Agenda Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.agenda_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  agenda_title: prismic.KeyTextField;

  /**
   * Agenda Text field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.agenda_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  agenda_text: prismic.RichTextField;

  /**
   * Main image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Metadata documents
 */
interface MetadataDocumentData {
  /**
   * Favicon field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Title field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Description field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Share Image field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.share_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  share_image: prismic.ImageField<never>;
}

/**
 * Metadata document from Prismic
 *
 * - **API ID**: `metadata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MetadataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MetadataDocumentData>,
    "metadata",
    Lang
  >;

/**
 * Item in *Primary Navigation → Links menu*
 */
export interface NavigationDocumentDataLinksMenuItem {
  /**
   * Label Menu field in *Primary Navigation → Links menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links_menu[].label_menu
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_menu: prismic.KeyTextField;

  /**
   * URL link field in *Primary Navigation → Links menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links_menu[].url_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_link: prismic.LinkField;
}

/**
 * Content for Primary Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Pact Title field in *Primary Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.pact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pact_title: prismic.KeyTextField;

  /**
   * Pact Link field in *Primary Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.pact_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pact_link: prismic.LinkField;

  /**
   * SOF title field in *Primary Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.sof_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sof_title: prismic.KeyTextField;

  /**
   * SOF link field in *Primary Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.sof_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sof_link: prismic.LinkField;

  /**
   * Links menu field in *Primary Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_menu: prismic.GroupField<Simplify<NavigationDocumentDataLinksMenuItem>>;
}

/**
 * Primary Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | DownloadsSlice
  | NextEventSlice
  | EmbeddedVideoSlice
  | SpeakersSlice
  | AnnouncementsSlice
  | ScheduleSlice;

/**
 * Content for Events documents
 */
interface PageDocumentData {
  /**
   * Label Event field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.label_event
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_event: prismic.KeyTextField;

  /**
   * Hero image field in *Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Title one field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_one: prismic.KeyTextField;

  /**
   * Title two field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_two: prismic.KeyTextField;

  /**
   * Title three field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_three
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_three: prismic.KeyTextField;

  /**
   * Agency field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agency
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  agency: prismic.KeyTextField;

  /**
   * Location field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Date field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Focal Point field in *Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.focal_point
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  focal_point: prismic.RichTextField;

  /**
   * Overview Primary text field in *Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.overview_primary_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  overview_primary_text: prismic.RichTextField;

  /**
   * Overview Secondary Text field in *Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.overview_secondary_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  overview_secondary_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Events document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type RegistrationPageDocumentDataSlicesSlice =
  | DontMissAnythingSlice
  | FaqsSlice;

/**
 * Content for Registration Page documents
 */
interface RegistrationPageDocumentData {
  /**
   * Location field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Date field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Title line 1 field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.title_line_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_1: prismic.KeyTextField;

  /**
   * Title line 2 field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.title_line_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_2: prismic.KeyTextField;

  /**
   * Title line 3 field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.title_line_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_3: prismic.KeyTextField;

  /**
   * Description hero field in *Registration Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.description_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_hero: prismic.RichTextField;

  /**
   * Link to registration field in *Registration Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.link_to_registration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_registration: prismic.LinkField;

  /**
   * Image QR App field in *Registration Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.image_qr_app
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_qr_app: prismic.ImageField<never>;

  /**
   * Title App field in *Registration Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.title_app
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_app: prismic.RichTextField;

  /**
   * Description App field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.description_app
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_app: prismic.KeyTextField;

  /**
   * Link Apple Store field in *Registration Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.link_apple_store
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_apple_store: prismic.LinkField;

  /**
   * Link Play Store field in *Registration Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.link_play_store
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_play_store: prismic.LinkField;

  /**
   * Slice Zone field in *Registration Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RegistrationPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: registration_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Registration Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: registration_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Registration Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: registration_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Registration Page document from Prismic
 *
 * - **API ID**: `registration_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RegistrationPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RegistrationPageDocumentData>,
    "registration_page",
    Lang
  >;

/**
 * Item in *Root page → Card Group*
 */
export interface RootPageDocumentDataCardGroupItem {
  /**
   * Date field in *Root page → Card Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.card_group[].date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Title field in *Root page → Card Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.card_group[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL Link field in *Root page → Card Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.card_group[].url_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_link: prismic.LinkField;
}

type RootPageDocumentDataSlicesSlice = never;

/**
 * Content for Root page documents
 */
interface RootPageDocumentData {
  /**
   * Title one field in *Root page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.title_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_one: prismic.KeyTextField;

  /**
   * Title two field in *Root page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.title_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_two: prismic.KeyTextField;

  /**
   * Description field in *Root page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Card Group field in *Root page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.card_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card_group: prismic.GroupField<Simplify<RootPageDocumentDataCardGroupItem>>;

  /**
   * Slice Zone field in *Root page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RootPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Root page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: root_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Root page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: root_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Root page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: root_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Root page document from Prismic
 *
 * - **API ID**: `root_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RootPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RootPageDocumentData>,
    "root_page",
    Lang
  >;

/**
 * Item in *Secondary Navigation → Links Menu*
 */
export interface SecondaryNavigationDocumentDataLinksMenuItem {
  /**
   * Link Title field in *Secondary Navigation → Links Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_navigation.links_menu[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * Link url field in *Secondary Navigation → Links Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_navigation.links_menu[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;
}

/**
 * Content for Secondary Navigation documents
 */
interface SecondaryNavigationDocumentData {
  /**
   * Links Menu field in *Secondary Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_navigation.links_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_menu: prismic.GroupField<
    Simplify<SecondaryNavigationDocumentDataLinksMenuItem>
  >;
}

/**
 * Secondary Navigation document from Prismic
 *
 * - **API ID**: `secondary_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SecondaryNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SecondaryNavigationDocumentData>,
    "secondary_navigation",
    Lang
  >;

/**
 * Item in *Secondary Navigation Events  → Links Menu*
 */
export interface SecondaryNavigationEventsDocumentDataLinksMenuItem {
  /**
   * Link Title field in *Secondary Navigation Events  → Links Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_navigation_events.links_menu[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * Link URL field in *Secondary Navigation Events  → Links Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_navigation_events.links_menu[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;
}

/**
 * Content for Secondary Navigation Events  documents
 */
interface SecondaryNavigationEventsDocumentData {
  /**
   * Links Menu field in *Secondary Navigation Events *
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_navigation_events.links_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_menu: prismic.GroupField<
    Simplify<SecondaryNavigationEventsDocumentDataLinksMenuItem>
  >;
}

/**
 * Secondary Navigation Events  document from Prismic
 *
 * - **API ID**: `secondary_navigation_events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SecondaryNavigationEventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SecondaryNavigationEventsDocumentData>,
    "secondary_navigation_events",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomeDocument
  | MetadataDocument
  | NavigationDocument
  | PageDocument
  | RegistrationPageDocument
  | RootPageDocument
  | SecondaryNavigationDocument
  | SecondaryNavigationEventsDocument;

/**
 * Item in *Agenda → Default → Primary → Card group*
 */
export interface AgendaSliceDefaultPrimaryCardGroupItem {
  /**
   * subtitle field in *Agenda → Default → Primary → Card group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.card_group[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * paragraph field in *Agenda → Default → Primary → Card group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.card_group[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * xl font size field in *Agenda → Default → Primary → Card group*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: agenda.default.primary.card_group[].xl_font_size
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  xl_font_size: prismic.BooleanField;

  /**
   * link field in *Agenda → Default → Primary → Card group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.card_group[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Hover Image field in *Agenda → Default → Primary → Card group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.card_group[].hover_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hover_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Agenda → Default → Primary*
 */
export interface AgendaSliceDefaultPrimary {
  /**
   * Title field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Background symbol field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.bg_symbol
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_symbol: prismic.ImageField<never>;

  /**
   * Card group field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.card_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card_group: prismic.GroupField<
    Simplify<AgendaSliceDefaultPrimaryCardGroupItem>
  >;
}

/**
 * Default variation for Agenda Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AgendaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AgendaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Agenda*
 */
type AgendaSliceVariation = AgendaSliceDefault;

/**
 * Agenda Shared Slice
 *
 * - **API ID**: `agenda`
 * - **Description**: Agenda
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AgendaSlice = prismic.SharedSlice<"agenda", AgendaSliceVariation>;

/**
 * Item in *Announcements → Default → Primary → Announcements*
 */
export interface AnnouncementsSliceDefaultPrimaryAnnouncementsItem {
  /**
   * display image field in *Announcements → Default → Primary → Announcements*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: announcements.default.primary.announcements[].display_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_image: prismic.BooleanField;

  /**
   * Image field in *Announcements → Default → Primary → Announcements*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.announcements[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * source field in *Announcements → Default → Primary → Announcements*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.announcements[].source
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  source: prismic.EmbedField;

  /**
   * Subtitle field in *Announcements → Default → Primary → Announcements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.announcements[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Paragraph field in *Announcements → Default → Primary → Announcements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.announcements[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Button link field in *Announcements → Default → Primary → Announcements*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.announcements[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Announcement Button text field in *Announcements → Default → Primary → Announcements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.announcements[].announcement_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  announcement_button_text: prismic.KeyTextField;
}

/**
 * Primary content in *Announcements → Default → Primary*
 */
export interface AnnouncementsSliceDefaultPrimary {
  /**
   * Title field in *Announcements → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title 2 field in *Announcements → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * Announcements field in *Announcements → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements.default.primary.announcements[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  announcements: prismic.GroupField<
    Simplify<AnnouncementsSliceDefaultPrimaryAnnouncementsItem>
  >;
}

/**
 * Default variation for Announcements Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnnouncementsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Announcements*
 */
type AnnouncementsSliceVariation = AnnouncementsSliceDefault;

/**
 * Announcements Shared Slice
 *
 * - **API ID**: `announcements`
 * - **Description**: Announcements
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementsSlice = prismic.SharedSlice<
  "announcements",
  AnnouncementsSliceVariation
>;

/**
 * Primary content in *DontMissAnything → Default → Primary*
 */
export interface DontMissAnythingSliceDefaultPrimary {
  /**
   * Title field in *DontMissAnything → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dont_miss_anything.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *DontMissAnything → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dont_miss_anything.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Registration link field in *DontMissAnything → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: dont_miss_anything.default.primary.registration_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  registration_link: prismic.LinkField;

  /**
   * Symbol top right field in *DontMissAnything → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dont_miss_anything.default.primary.symbol_top_right
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  symbol_top_right: prismic.ImageField<never>;

  /**
   * Symbol bottom left field in *DontMissAnything → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dont_miss_anything.default.primary.symbol_bottom_left
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  symbol_bottom_left: prismic.ImageField<never>;
}

/**
 * Default variation for DontMissAnything Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DontMissAnythingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DontMissAnythingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DontMissAnything*
 */
type DontMissAnythingSliceVariation = DontMissAnythingSliceDefault;

/**
 * DontMissAnything Shared Slice
 *
 * - **API ID**: `dont_miss_anything`
 * - **Description**: DontMissAnything
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DontMissAnythingSlice = prismic.SharedSlice<
  "dont_miss_anything",
  DontMissAnythingSliceVariation
>;

/**
 * Item in *Downloads → Default → Primary → Documents*
 */
export interface DownloadsSliceDefaultPrimaryDocumentsItem {
  /**
   * Subtitle field in *Downloads → Default → Primary → Documents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.documents[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *Downloads → Default → Primary → Documents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.documents[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Banner Image field in *Downloads → Default → Primary → Documents*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.documents[].banner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_image: prismic.ImageField<never>;

  /**
   * Download text field in *Downloads → Default → Primary → Documents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.documents[].download_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  download_text: prismic.KeyTextField;

  /**
   * Download url field in *Downloads → Default → Primary → Documents*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.documents[].download_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  download_url: prismic.LinkField;
}

/**
 * Primary content in *Downloads → Default → Primary*
 */
export interface DownloadsSliceDefaultPrimary {
  /**
   * Light Background Color field in *Downloads → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: downloads.default.primary.light_background_color
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  light_background_color: prismic.BooleanField;

  /**
   * Title field in *Downloads → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Downloads → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Documents field in *Downloads → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: downloads.default.primary.documents[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  documents: prismic.GroupField<
    Simplify<DownloadsSliceDefaultPrimaryDocumentsItem>
  >;
}

/**
 * Default variation for Downloads Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DownloadsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DownloadsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Downloads*
 */
type DownloadsSliceVariation = DownloadsSliceDefault;

/**
 * Downloads Shared Slice
 *
 * - **API ID**: `downloads`
 * - **Description**: Downloads
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DownloadsSlice = prismic.SharedSlice<
  "downloads",
  DownloadsSliceVariation
>;

/**
 * Item in *EmbeddedVideo → Default → Primary → sources*
 */
export interface EmbeddedVideoSliceDefaultPrimarySourcesItem {
  /**
   * source field in *EmbeddedVideo → Default → Primary → sources*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: embedded_video.default.primary.sources[].source
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  source: prismic.EmbedField;
}

/**
 * Primary content in *EmbeddedVideo → Default → Primary*
 */
export interface EmbeddedVideoSliceDefaultPrimary {
  /**
   * title1 field in *EmbeddedVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embedded_video.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * title2 field in *EmbeddedVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embedded_video.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * text field in *EmbeddedVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embedded_video.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * sources field in *EmbeddedVideo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: embedded_video.default.primary.sources[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sources: prismic.GroupField<
    Simplify<EmbeddedVideoSliceDefaultPrimarySourcesItem>
  >;
}

/**
 * Default variation for EmbeddedVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbeddedVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmbeddedVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EmbeddedVideo*
 */
type EmbeddedVideoSliceVariation = EmbeddedVideoSliceDefault;

/**
 * EmbeddedVideo Shared Slice
 *
 * - **API ID**: `embedded_video`
 * - **Description**: EmbeddedVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbeddedVideoSlice = prismic.SharedSlice<
  "embedded_video",
  EmbeddedVideoSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → Faqs*
 */
export interface FaqsSliceDefaultPrimaryFaqsItem {
  /**
   * Category name field in *Faqs → Default → Primary → Faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].category_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_name: prismic.KeyTextField;

  /**
   * Question title field in *Faqs → Default → Primary → Faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].question_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question_title: prismic.KeyTextField;

  /**
   * Question response field in *Faqs → Default → Primary → Faqs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].question_response
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question_response: prismic.RichTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Display title field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: faqs.default.primary.display_title
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_title: prismic.BooleanField;

  /**
   * Faqs field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *NextEvent → Default → Primary*
 */
export interface NextEventSliceDefaultPrimary {
  /**
   * Background Image field in *NextEvent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: next_event.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title 1 field in *NextEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: next_event.default.primary.title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_1: prismic.KeyTextField;

  /**
   * Title 2 field in *NextEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: next_event.default.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * Text field in *NextEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: next_event.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Button Text field in *NextEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: next_event.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *NextEvent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: next_event.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for NextEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextEventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NextEventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NextEvent*
 */
type NextEventSliceVariation = NextEventSliceDefault;

/**
 * NextEvent Shared Slice
 *
 * - **API ID**: `next_event`
 * - **Description**: NextEvent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextEventSlice = prismic.SharedSlice<
  "next_event",
  NextEventSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Title field in *RichText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Schedule → Default → Primary → Agenda items*
 */
export interface ScheduleSliceDefaultPrimaryAgendaItemsItem {
  /**
   * Time field in *Schedule → Default → Primary → Agenda items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.agenda_items[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Events field in *Schedule → Default → Primary → Agenda items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.agenda_items[].events
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  events: prismic.RichTextField;

  /**
   * Speakers field in *Schedule → Default → Primary → Agenda items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.agenda_items[].speakers
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  speakers: prismic.RichTextField;

  /**
   * Room field in *Schedule → Default → Primary → Agenda items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.agenda_items[].room
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  room: prismic.KeyTextField;
}

/**
 * Primary content in *Schedule → Default → Primary*
 */
export interface ScheduleSliceDefaultPrimary {
  /**
   * Title field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Has rooms field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: schedule.default.primary.has_rooms
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_rooms: prismic.BooleanField;

  /**
   * Time title field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.time_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time_title: prismic.KeyTextField;

  /**
   * Events title field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.events_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  events_title: prismic.KeyTextField;

  /**
   * Speakers Title field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.speakers_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speakers_title: prismic.KeyTextField;

  /**
   * Room title field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.room_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  room_title: prismic.KeyTextField;

  /**
   * Agenda items field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.agenda_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  agenda_items: prismic.GroupField<
    Simplify<ScheduleSliceDefaultPrimaryAgendaItemsItem>
  >;
}

/**
 * Default variation for Schedule Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScheduleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Schedule*
 */
type ScheduleSliceVariation = ScheduleSliceDefault;

/**
 * Schedule Shared Slice
 *
 * - **API ID**: `schedule`
 * - **Description**: Schedule
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleSlice = prismic.SharedSlice<
  "schedule",
  ScheduleSliceVariation
>;

/**
 * Item in *Speakers → Default → Primary → speakers*
 */
export interface SpeakersSliceDefaultPrimarySpeakersItem {
  /**
   * Speaker name field in *Speakers → Default → Primary → speakers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers.default.primary.speakers[].speaker_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speaker_name: prismic.KeyTextField;

  /**
   * Description field in *Speakers → Default → Primary → speakers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers.default.primary.speakers[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *Speakers → Default → Primary → speakers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers.default.primary.speakers[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Speakers → Default → Primary*
 */
export interface SpeakersSliceDefaultPrimary {
  /**
   * Title field in *Speakers → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Speakers → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * speakers field in *Speakers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers.default.primary.speakers[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  speakers: prismic.GroupField<
    Simplify<SpeakersSliceDefaultPrimarySpeakersItem>
  >;
}

/**
 * Default variation for Speakers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeakersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpeakersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Speakers*
 */
type SpeakersSliceVariation = SpeakersSliceDefault;

/**
 * Speakers Shared Slice
 *
 * - **API ID**: `speakers`
 * - **Description**: Speakers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeakersSlice = prismic.SharedSlice<
  "speakers",
  SpeakersSliceVariation
>;

/**
 * Item in *WhenandWhere → Default → Primary → Questions*
 */
export interface WhenandWhereSliceDefaultPrimaryQuestionsItem {
  /**
   * Question Title field in *WhenandWhere → Default → Primary → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whenand_where.default.primary.questions[].question_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question_title: prismic.KeyTextField;

  /**
   * Question response field in *WhenandWhere → Default → Primary → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whenand_where.default.primary.questions[].question_response
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question_response: prismic.KeyTextField;
}

/**
 * Primary content in *WhenandWhere → Default → Primary*
 */
export interface WhenandWhereSliceDefaultPrimary {
  /**
   * Image field in *WhenandWhere → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: whenand_where.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Symbol field in *WhenandWhere → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: whenand_where.default.primary.bg_symbol
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_symbol: prismic.ImageField<never>;

  /**
   * Questions field in *WhenandWhere → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: whenand_where.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<
    Simplify<WhenandWhereSliceDefaultPrimaryQuestionsItem>
  >;
}

/**
 * Default variation for WhenandWhere Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhenandWhereSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhenandWhereSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhenandWhere*
 */
type WhenandWhereSliceVariation = WhenandWhereSliceDefault;

/**
 * WhenandWhere Shared Slice
 *
 * - **API ID**: `whenand_where`
 * - **Description**: WhenandWhere
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhenandWhereSlice = prismic.SharedSlice<
  "whenand_where",
  WhenandWhereSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinksItem,
      FooterDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MetadataDocument,
      MetadataDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksMenuItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      RegistrationPageDocument,
      RegistrationPageDocumentData,
      RegistrationPageDocumentDataSlicesSlice,
      RootPageDocument,
      RootPageDocumentData,
      RootPageDocumentDataCardGroupItem,
      RootPageDocumentDataSlicesSlice,
      SecondaryNavigationDocument,
      SecondaryNavigationDocumentData,
      SecondaryNavigationDocumentDataLinksMenuItem,
      SecondaryNavigationEventsDocument,
      SecondaryNavigationEventsDocumentData,
      SecondaryNavigationEventsDocumentDataLinksMenuItem,
      AllDocumentTypes,
      AgendaSlice,
      AgendaSliceDefaultPrimaryCardGroupItem,
      AgendaSliceDefaultPrimary,
      AgendaSliceVariation,
      AgendaSliceDefault,
      AnnouncementsSlice,
      AnnouncementsSliceDefaultPrimaryAnnouncementsItem,
      AnnouncementsSliceDefaultPrimary,
      AnnouncementsSliceVariation,
      AnnouncementsSliceDefault,
      DontMissAnythingSlice,
      DontMissAnythingSliceDefaultPrimary,
      DontMissAnythingSliceVariation,
      DontMissAnythingSliceDefault,
      DownloadsSlice,
      DownloadsSliceDefaultPrimaryDocumentsItem,
      DownloadsSliceDefaultPrimary,
      DownloadsSliceVariation,
      DownloadsSliceDefault,
      EmbeddedVideoSlice,
      EmbeddedVideoSliceDefaultPrimarySourcesItem,
      EmbeddedVideoSliceDefaultPrimary,
      EmbeddedVideoSliceVariation,
      EmbeddedVideoSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqsItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      NextEventSlice,
      NextEventSliceDefaultPrimary,
      NextEventSliceVariation,
      NextEventSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ScheduleSlice,
      ScheduleSliceDefaultPrimaryAgendaItemsItem,
      ScheduleSliceDefaultPrimary,
      ScheduleSliceVariation,
      ScheduleSliceDefault,
      SpeakersSlice,
      SpeakersSliceDefaultPrimarySpeakersItem,
      SpeakersSliceDefaultPrimary,
      SpeakersSliceVariation,
      SpeakersSliceDefault,
      WhenandWhereSlice,
      WhenandWhereSliceDefaultPrimaryQuestionsItem,
      WhenandWhereSliceDefaultPrimary,
      WhenandWhereSliceVariation,
      WhenandWhereSliceDefault,
    };
  }
}
