// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  agenda: defineAsyncComponent(() => import("./Agenda/index.vue")),
  announcements: defineAsyncComponent(
    () => import("./Announcements/index.vue"),
  ),
  downloads: defineAsyncComponent(() => import("./Downloads/index.vue")),
  embedded_video: defineAsyncComponent(
    () => import("./EmbeddedVideo/index.vue"),
  ),
  faqs: defineAsyncComponent(() => import("./Faqs/index.vue")),
  next_event: defineAsyncComponent(() => import("./NextEvent/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  schedule: defineAsyncComponent(() => import("./Schedule/index.vue")),
  speakers: defineAsyncComponent(() => import("./Speakers/index.vue")),
  whenand_where: defineAsyncComponent(() => import("./WhenandWhere/index.vue")),
});
